name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag_name'
        required: true
      registry:
        description: 'bazel central registry target'
        required: false
        default: 'publish-to-bcr-dev/bazel-central-registry'        

permissions:
  id-token: write
  attestations: write

jobs:
  publish:
    uses: publish-to-bcr-dev/.github/.github/workflows/publish.yaml@3976ed46abc50f53ad03a88d486ec6bc59f8ac81
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: ${{ inputs.registry }}