name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag_name'
        required: true
      registry:
        description: 'bazel central registry target'
        required: false
        default: 'fweikert/bazel-central-registry'
      registry-fork:
        description: ''
        required: true
        default: publish-to-bcr-dev/bazel-central-registry

permissions:
  id-token: write
  attestations: write

jobs:
  publish:
    uses: publish-to-bcr-dev/.github/.github/workflows/publish.yaml@2e2115a892934f499ecb65e250d14b02ad9520df
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: ${{ inputs.registry }}
      registry-fork: ${{ inputs.registry-fork }}